### ISSUE TITLE
Ненужная конвертация и потеря альфа-канала

### ISSUE THREAD

**Issue by devcooch** [vas3k/pepic#4]
При загрузке картинки PNG небольшого размера и с альфа-каналом - конвертирует в JPEG и теряет альфа-канал.

**Comment by devcooch** [comment]
Или это делает клуб?

**Comment by vas3k** [comment]
Это же настройка такая — конвертировать или нет. Блог оставляет оригиналы. Клуб конвертирует все в JPEG и сильно сжимает, ибо UGC
